import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import CommonLayout from "@/components/commonLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Login Test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CommonLayout>{children}</CommonLayout>
      </body>
    </html>
  );
}
